# Analise exploratória de dados

O dataset utilizado é de origem KAlimentos contendo dados de vendas a consumidores não identificados em feiras da região.

## Informações

### Contexto

**Qual é o objetivo da analise:**

O objetivo é tirar insites dos dados existentes em busca de padrões mas mais do que isso criar um modelo de recomendação de produtos a serem recomendados antes da finalização da compra, assim obtendo um possivel aumento de venda de produtos ao identificar clientes com maior possibilidade de compra alem de tambem identificar combos de recomendações.

**Qual o enredo do Objetivo:**

O enredo é aumentar o ticket medio das vendas tendo acertividade no destaque de certos produtos com bases nos dados historicos.

**Como funciona o Processo:**

O processo é que no PDV (ponto de venda) das feiras/eventos é realzado o registro das vendas tendo como principal foco acompanhamento das vendas como dados de faturamento (algo requisitado diariamente pelos organizadores das vendas) alem do controle de estoque do evento.

**Publico alvo:**

Pessoas das mais diversas que vão a especificos eventos/feiras e feirantes/vendedores

**Forma de entrega:**

Um modelo/sistema de recomendação que ao finalizar um pedido de venda recomenda produto(s) ou não a serem oferecidos. 

### Dados

**Quais são:**

**Como foram coletados:**

**Amostra/População:**

**Qualidade:**

**Estrutura:**

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('./studing/KalimentosFeirasVendas.csv')

df.dtypes

pedido_id                         str
pedido_valor_total            float64
pedido_data                       str
pedido_tipo_desconto              str
pedido_valor_desconto         float64
pedido_subtotal                 int64
pedido_vendedor                   str
pedido_metodo_pagamento           str
item_pedido_nome_produto          str
item_pedido_quantidade          int64
item_pedido_preco_unitario    float64
item_pedido_user_id               str
evento_nome                       str
evento_data_inicio                str
evento_data_fim                   str
dtype: object

In [138]:
df.head()

,pedido_id,pedido_valor_total,pedido_data,pedido_tipo_desconto,pedido_valor_desconto,pedido_subtotal,pedido_vendedor,pedido_metodo_pagamento,item_pedido_nome_produto,item_pedido_quantidade,item_pedido_preco_unitario,item_pedido_user_id,evento_nome,evento_data_inicio,evento_data_fim
0,a231f36f-be88-492c-b719-23830b22fb4b,20.0,2026-03-09 17:31:54.325-03,%,0.0,20,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Dinheiro,Alfajor Preto (Pacote x4),1,20.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto,2026-03-08,2026-03-13
1,d47eb20b-e24f-4c70-92f9-9b554eb8f280,15.0,2026-03-10 10:27:12.241-03,%,0.0,15,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Dinheiro,Cuca Enrolada de Amendoim,1,15.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto,2026-03-08,2026-03-13
2,d3b5b66d-d9e1-4924-b507-144e0e0b9ef9,15.0,2026-03-10 11:17:14.665-03,%,0.0,15,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Cartão,Cuca Enrolada de Amendoim,1,15.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto,2026-03-08,2026-03-13
3,5b4e4307-89b1-4601-bba3-04be3a33a5ea,13.0,2026-03-10 12:02:08.319-03,%,0.0,13,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Cartão,Alfajor Preto,1,6.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto,2026-03-08,2026-03-13
4,5b4e4307-89b1-4601-bba3-04be3a33a5ea,13.0,2026-03-10 12:02:08.319-03,%,0.0,13,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Cartão,Cri-Cri 200g,1,7.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto,2026-03-08,2026-03-13

In [139]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3115 entries, 0 to 3114
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   pedido_id                   3115 non-null   str
 1   pedido_valor_total          3115 non-null   float64
 2   pedido_data                 3115 non-null   str
 3   pedido_tipo_desconto        3115 non-null   str
 4   pedido_valor_desconto       3115 non-null   float64
 5   pedido_subtotal             3115 non-null   int64
 6   pedido_vendedor             3115 non-null   str
 7   pedido_metodo_pagamento     3115 non-null   str
 8   item_pedido_nome_produto    3115 non-null   str
 9   item_pedido_quantidade      3115 non-null   int64
 10  item_pedido_preco_unitario  3115 non-null   float64
 11  item_pedido_user_id         3115 non-null   str
 12  evento_nome                 3115 non-null   str
 13  evento_data_inicio          3115 non-null   str
 14  evento_data_fim             2504 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 365.2 KB

## Remoção de dados

In [140]:
df = df.drop(['evento_data_fim','evento_data_inicio'], axis=1)

In [141]:
df.describe()

,pedido_valor_total,pedido_valor_desconto,pedido_subtotal,item_pedido_quantidade,item_pedido_preco_unitario
count,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000
mean,46.967859,0.363441,47.331300,2.666774,13.286998
std,210.062853,2.752272,210.390628,8.485927,8.653962
min,0.000000,0.000000,5.000000,0.000000,4.000000
25%,15.000000,0.000000,15.000000,1.000000,6.000000
50%,25.000000,0.000000,25.000000,1.000000,8.000000
75%,35.000000,0.000000,35.000000,3.000000,25.000000
max,3693.000000,83.000000,3696.000000,348.000000,80.000000

In [142]:
df.query('pedido_tipo_desconto == "%" and pedido_valor_desconto > 0')

,pedido_id,pedido_valor_total,pedido_data,pedido_tipo_desconto,pedido_valor_desconto,pedido_subtotal,pedido_vendedor,pedido_metodo_pagamento,item_pedido_nome_produto,item_pedido_quantidade,item_pedido_preco_unitario,item_pedido_user_id,evento_nome
1536,ca605a42-8d41-4c35-a968-18971c6cc0b0,5.88,2026-06-04 16:06:39.202-03,%,0.12,6,3f621f3e-720d-4c68-b436-eaac939ec515,Dinheiro,Alfajor Preto,1,6.0,3f621f3e-720d-4c68-b436-eaac939ec515,EXPOBENTO

In [143]:
df.query('pedido_valor_total > pedido_subtotal').head()

Empty DataFrame
Columns: [pedido_id, pedido_valor_total, pedido_data, pedido_tipo_desconto, pedido_valor_desconto, pedido_subtotal, pedido_vendedor, pedido_metodo_pagamento, item_pedido_nome_produto, item_pedido_quantidade, item_pedido_preco_unitario, item_pedido_user_id, evento_nome]
Index: []

In [144]:
df.rename(columns={'pedido_valor_total':'pedido_valor_final'}, inplace=True)
df.head()

,pedido_id,pedido_valor_final,pedido_data,pedido_tipo_desconto,pedido_valor_desconto,pedido_subtotal,pedido_vendedor,pedido_metodo_pagamento,item_pedido_nome_produto,item_pedido_quantidade,item_pedido_preco_unitario,item_pedido_user_id,evento_nome
0,a231f36f-be88-492c-b719-23830b22fb4b,20.0,2026-03-09 17:31:54.325-03,%,0.0,20,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Dinheiro,Alfajor Preto (Pacote x4),1,20.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto
1,d47eb20b-e24f-4c70-92f9-9b554eb8f280,15.0,2026-03-10 10:27:12.241-03,%,0.0,15,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Dinheiro,Cuca Enrolada de Amendoim,1,15.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto
2,d3b5b66d-d9e1-4924-b507-144e0e0b9ef9,15.0,2026-03-10 11:17:14.665-03,%,0.0,15,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Cartão,Cuca Enrolada de Amendoim,1,15.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto
3,5b4e4307-89b1-4601-bba3-04be3a33a5ea,13.0,2026-03-10 12:02:08.319-03,%,0.0,13,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Cartão,Alfajor Preto,1,6.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto
4,5b4e4307-89b1-4601-bba3-04be3a33a5ea,13.0,2026-03-10 12:02:08.319-03,%,0.0,13,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,Cartão,Cri-Cri 200g,1,7.0,aa4d1cfe-c6c1-4fd8-8c4b-2b1b9942884c,ExpoDireto

In [145]:
df['pedido_data'] = pd.to_datetime(df['pedido_data'],format='mixed')

In [146]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3115 entries, 0 to 3114
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   pedido_id                   3115 non-null   str
 1   pedido_valor_final          3115 non-null   float64
 2   pedido_data                 3115 non-null   datetime64[us, UTC-03:00]
 3   pedido_tipo_desconto        3115 non-null   str
 4   pedido_valor_desconto       3115 non-null   float64
 5   pedido_subtotal             3115 non-null   int64
 6   pedido_vendedor             3115 non-null   str
 7   pedido_metodo_pagamento     3115 non-null   str
 8   item_pedido_nome_produto    3115 non-null   str
 9   item_pedido_quantidade      3115 non-null   int64
 10  item_pedido_preco_unitario  3115 non-null   float64
 11  item_pedido_user_id         3115 non-null   str
 12  evento_nome                 3115 non-null   str
dtypes: datetime64[us, UTC-03:00](1), float64(3), int64(2), str(7)
memory usage: 316.5 KB

In [149]:
df['item_pedido_nome_produto'].value_counts()

item_pedido_nome_produto
Cuca Alemã                                   788
Cuca Enrolada de Amendoim                    473
Rapadura de Melado                           286
Rapadura Assada (Pacote x6)                  253
Rapadura Assada                              203
Rapadura de Melado (Pacote x3)               198
Alfajor Preto                                189
Alfajor Preto (Pacote x4)                    152
Cri-Cri 200g                                 104
Amendoim Temperado                            68
Alfajor Branco                                64
Bolacha de manteiga                           58
Amendoim salgado e temperado                  38
Pé-de-Moleque                                 36
Rapadura de Melado Grão Moído                 30
Alfajor Preto (Bandeja x5)                    22
Bolacha Cobertura Chocolate                   22
Alfajor Branco (Pacote x4)                    19
Rapadura de Melado Grão Moído (Pacote x1)     16
Alfajor Preto (Display x1)                    14
Carrapinha                                    13
Alfajor Preto (Caixa x16)                     12
Alfajor Branco (Bandeja x5)                   12
Cuca Enrolada de Amendoim (Pacote x2)          9
Amendoim Temperado 100g                        9
Bolacha de Milho                               8
Alfajor Branco (Display x1)                    6
Cuca Enrolada de Chocolate                     5
Alfajor Preto (Display x16)                    5
Alfajor Branco (Caixa x16)                     2
Rapadura Assada (Caixa x20)                    1
Name: count, dtype: int64