In [ ]:
# Bloco de configuração
# Este comando baixa o nosso conjunto de dados do IMDB e o salva com o nome 'imdb.csv'
# para que possamos usá-lo nos exemplos.

!wget -q -O imdb.csv https://raw.githubusercontent.com/curso-r/202209-r4ds-1/refs/heads/main/dados/imdb.csv

# Aula: Manipulação de Dados com Python (Pandas)

 O pilar da manipulação de dados em Python é a biblioteca **Pandas**. Ela consegue ler uma vasta gama de formatos, como CSV, TXT, Excel, JSON, entre outros.

Documentação para o [Pandas](https://pandas.pydata.org/docs/index.html)

# 1. Importação de Dados



O objeto principal que o Pandas cria e manipula é o **DataFrame** (tabular)

In [ ]:
# Para começar, vamos importar a biblioteca pandas. A convenção é importá-la com o apelido 'pd'.
import pandas as pd

# Importando dados csv com Pandas

# A função principal para ler arquivos delimitados (como .csv e .txt) é a pd.read_csv()

# Vamos carregar o arquivo que baixamos.
imdb_df = pd.read_csv('/content/imdb.csv')

# visualisar primera linhas, display pra ficar elegante no colab
display(imdb_df.head())

#visão geral
imdb_df.info()

,id_filme,titulo,ano,data_lancamento,generos,duracao,pais,idioma,orcamento,receita,receita_eua,nota_imdb,num_avaliacoes,direcao,roteiro,producao,elenco,descricao,num_criticas_publico,num_criticas_critica
0,tt0023352,Prestige,1931.0,1932-01-22,"Adventure, Drama",71,USA,English,NaN,NaN,NaN,5.7,240,Tay Garnett,"Harry Hervey, Tay Garnett",RKO Pathé Pictures,"Ann Harding, Adolphe Menjou, Melvyn Douglas, I...",A woman travels to a French penal colony in In...,12.0,2.0
1,tt0037946,Nob Hill,1945.0,1945-11-15,"Drama, Musical",95,USA,English,NaN,NaN,NaN,6.3,246,Henry Hathaway,"Wanda Tuchock, Norman Reilly Raine",Twentieth Century Fox,"George Raft, Joan Bennett, Vivian Blaine, Pegg...",The owner of a San Francisco saloon yearns to ...,11.0,2.0
2,tt0216204,The Shade,1999.0,2000-03-01,Drama,83,USA,English,400000.0,NaN,NaN,7.1,102,Raphaël Nadjari,"Fyodor Dostoevsky, Raphaël Nadjari",Filmaker,"Richard Edson, Lorie Marino, Jeff Ware, Barbar...",NaN,1.0,1.0
3,tt0171889,Viewer Discretion Advised,1998.0,2012-05-01,"Comedy, Horror",105,USA,English,NaN,NaN,NaN,3.4,111,"Eddie Beverly Jr., Tommy Blaze","Tommy Blaze, Philip Morton",Troma Entertainment,"Ken Donovan, Philip Morton, Caroline Jett, Tom...",Ted Smith becomes trapped in the TV shows he w...,5.0,3.0
4,tt0092699,Broadcast News,1987.0,1988-04-01,"Comedy, Drama, Romance",133,USA,"English, Spanish, French, German",20000000.0,67331309.0,51249404.0,7.2,26257,James L. Brooks,James L. Brooks,Amercent Films,"William Hurt, Albert Brooks, Holly Hunter, Rob...",Take two rival television reporters: one hands...,142.0,62.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28490 entries, 0 to 28489
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_filme              28490 non-null  object
 1   titulo                28490 non-null  object
 2   ano                   28489 non-null  float64
 3   data_lancamento       28490 non-null  object
 4   generos               28490 non-null  object
 5   duracao               28490 non-null  int64
 6   pais                  28490 non-null  object
 7   idioma                28131 non-null  object
 8   orcamento             10470 non-null  float64
 9   receita               7698 non-null   float64
 10  receita_eua           7556 non-null   float64
 11  nota_imdb             28490 non-null  float64
 12  num_avaliacoes        28490 non-null  int64
 13  direcao               28457 non-null  object
 14  roteiro               28289 non-null  object
 15  producao              27332 non-null  object
 16  elenco                28464 non-null  object
 17  descricao             28418 non-null  object
 18  num_criticas_publico  28186 non-null  float64
 19  num_criticas_critica  26618 non-null  float64
dtypes: float64(7), int64(2), object(11)
memory usage: 4.3+ MB

### Parâmetros úteis na importação

podemos ter problemas ao importar arquivos (separador incorreto, casas decimais com vírgula, etc.). A função `read_csv` tem argumentos para lidar com isso:

* `sep`: Define o separador de colunas (ex: `sep=';'`).
* `decimal`: Define o caractere usado para separar as casas decimais (ex: `decimal=','`).
* `encoding`: Resolve problemas de codificação de caracteres (ex: `'latin-1'`, `'utf-8'`).
* `skiprows`: Pula um número de linhas do início do arquivo.
* `na_values`: Uma lista de strings que devem ser consideradas como `NA`/`NaN` (ex: `na_values=['-999', 'sem info']`).
* `dtype`: Permite especificar o tipo de cada coluna.

In [ ]:
#Podemos gerar nosso dataframe apratir de um dicionario de listas (chaves são os nomes das variaveis)
dados_alunos = {
    'Nome': ['Ana', 'Bruno', 'Carla', 'Daniel', 'Marco'],
    'Matricula': [202501, 202502, 202503, 202504,202505],
    'Nota_P1': [8.5, 7.0, 9.5, 6.0,"NA"],
    'Nota_P2': [9.0, 8.0, 8.5, 7.5,"NA"]
}

# Criando o DataFrame a partir do dicionário
pd.DataFrame(dados_alunos)

     Nome  Matricula Nota_P1 Nota_P2
0     Ana     202501     8.5     9.0
1   Bruno     202502     7.0     8.0
2   Carla     202503     9.5     8.5
3  Daniel     202504     6.0     7.5
4   Marco     202505      NA      NA

---

# 2. Manipulação de Dados com Pandas

###Encadeamento de métodos

Para tornar o codigo mais legivel, visto que a maioria das funções de manipulação do 'pandas' são *metodos* de um DataFrame, podemos chamá-las em sequência, uma após a outra por meio de **encadeamento de metodos** (Method chaining)

**Receita de bolo em Python (com method chaining):** recipiente.acrescente("farinha", "ovo", "Acucar").bata().asse(time="45", temp="200")

 O `pandas` possui inumeros métodos, podemos descar.

| Método| Descrição |
|---|---|
| `df[['col1', 'col2']]` ou `df.drop()` | Seleciona colunas |
| `df.query()` ou `df[condição]` | Filtra linhas |
| `df.sort_values()` | Ordena o DataFrame |
| `df.assign()` ou `df['nova_col'] = ...` | Cria ou modifica colunas |
| `df.groupby()` | Agrupa o DataFrame |
| `.agg()` ou outras agregações (`.mean()`, `.sum()`) | Sumariza dados agrupados |
| `pd.merge(df1, df2, on='chave', how='left')` | Junta DataFrames |
| `df['col'].value_counts()` | Conta as ocorrencias de um elemento na coluna
|`df.explode('col')`| duplica a linha para cada elemento da lista

Vamos usar o nosso DataFrame `imdb_df` para praticar. Primeiro, vamos remover linhas com valores nulos em colunas importantes para facilitar os exemplos.

In [ ]:
# Renomeando colunas e removendo NAs
imdb_df = imdb_df.rename(columns={
    'id_filme': 'id',
    'orcamento': 'gastos'
}).dropna(subset=['titulo', 'direcao', 'gastos', 'receita', 'nota_imdb', 'ano'])

imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4732 entries, 4 to 28489
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4732 non-null   object
 1   titulo                4732 non-null   object
 2   ano                   4732 non-null   float64
 3   data_lancamento       4732 non-null   object
 4   generos               4732 non-null   object
 5   duracao               4732 non-null   int64
 6   pais                  4732 non-null   object
 7   idioma                4721 non-null   object
 8   gastos                4732 non-null   float64
 9   receita               4732 non-null   float64
 10  receita_eua           4372 non-null   float64
 11  nota_imdb             4732 non-null   float64
 12  num_avaliacoes        4732 non-null   int64
 13  direcao               4732 non-null   object
 14  roteiro               4730 non-null   object
 15  producao              4702 non-null   object
 16  elenco                4731 non-null   object
 17  descricao             4725 non-null   object
 18  num_criticas_publico  4727 non-null   float64
 19  num_criticas_critica  4713 non-null   float64
dtypes: float64(7), int64(2), object(11)
memory usage: 776.3+ KB

In [ ]:
# Convertendo ano para inteiro
imdb_df['ano'] = imdb_df['ano'].astype(int)

imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4732 entries, 4 to 28489
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4732 non-null   object
 1   titulo                4732 non-null   object
 2   ano                   4732 non-null   int64
 3   data_lancamento       4732 non-null   object
 4   generos               4732 non-null   object
 5   duracao               4732 non-null   int64
 6   pais                  4732 non-null   object
 7   idioma                4721 non-null   object
 8   gastos                4732 non-null   float64
 9   receita               4732 non-null   float64
 10  receita_eua           4372 non-null   float64
 11  nota_imdb             4732 non-null   float64
 12  num_avaliacoes        4732 non-null   int64
 13  direcao               4732 non-null   object
 14  roteiro               4730 non-null   object
 15  producao              4702 non-null   object
 16  elenco                4731 non-null   object
 17  descricao             4725 non-null   object
 18  num_criticas_publico  4727 non-null   float64
 19  num_criticas_critica  4713 non-null   float64
dtypes: float64(6), int64(3), object(11)
memory usage: 776.3+ KB

## Selecionar colunas

In [ ]:
# Seleção de colunas.
df_selecionado = imdb_df[['titulo', 'ano', 'direcao']]
df_selecionado.head()

                          titulo   ano                         direcao
4                 Broadcast News  1987                 James L. Brooks
11            Me, Myself & Irene  2000  Bobby Farrelly, Peter Farrelly
21                    No Way Out  1987                 Roger Donaldson
22  Welcome Home, Roscoe Jenkins  2008                  Malcolm D. Lee
25                 Pandora's Box  2002                       Rob Hardy

In [ ]:
# Quando temos muitas colunas, podemos selecionar por intervalo
# Para selecionar um intervalo de colunas (como generos:receita), usamos .loc
imdb_df.loc[:, 'generos':'receita'].head()

,generos,duracao,pais,idioma,gastos,receita
4,"Comedy, Drama, Romance",133,USA,"English, Spanish, French, German",20000000.0,67331309.0
11,Comedy,116,USA,"English, German",51000000.0,149270999.0
21,"Action, Crime, Drama",114,USA,"English, Russian",15000000.0,35509515.0
22,"Comedy, Romance",104,USA,English,35000000.0,43655418.0
25,"Drama, Thriller",103,USA,English,800000.0,881950.0

In [ ]:
# remover uma colunas ou colunas, usar .drop()
imdb_df.loc[:, 'generos':'receita'].drop(columns=['idioma']).head()

                   generos  duracao pais      gastos      receita
4   Comedy, Drama, Romance      133  USA  20000000.0   67331309.0
11                  Comedy      116  USA  51000000.0  149270999.0
21    Action, Crime, Drama      114  USA  15000000.0   35509515.0
22         Comedy, Romance      104  USA  35000000.0   43655418.0
25         Drama, Thriller      103  USA    800000.0     881950.0

In [ ]:
#  usamos .sort_values(). O argumento ascending=False psara fazer em ordem decrescente
imdb_df[['titulo', 'ano']].sort_values(by='ano', ascending=False).head()

                     titulo   ano
28302             Bloodshot  2020
20354              Unhinged  2020
19811       Force of Nature  2020
10693  Disturbing the Peace  2020
18821    Sex and the Future  2020

In [ ]:
# selecionar baseado em expreçẽos regulares, drop funciona idem
imdb_df.filter(regex='cao$') # que terminam em 'cao'
imdb_df.filter(regex='^d') # que iniica com'd'
imdb_df.drop(columns=imdb_df.filter(regex='^d').columns) # remover . columns fica com os nomes

,id,titulo,ano,generos,pais,idioma,gastos,receita,receita_eua,nota_imdb,num_avaliacoes,roteiro,producao,elenco,num_criticas_publico,num_criticas_critica,lucro
4,tt0092699,Broadcast News,1987,"Comedy, Drama, Romance",USA,"English, Spanish, French, German",20000000.0,67331309.0,51249404.0,7.2,26257,James L. Brooks,Amercent Films,"William Hurt, Albert Brooks, Holly Hunter, Rob...",142.0,62.0,47331309.0
11,tt0183505,"Me, Myself & Irene",2000,Comedy,USA,"English, German",51000000.0,149270999.0,90570999.0,6.6,219069,"Peter Farrelly, Mike Cerrone",Twentieth Century Fox,"Jim Carrey, Renée Zellweger, Anthony Anderson,...",502.0,161.0,98270999.0
21,tt0093640,No Way Out,1987,"Action, Crime, Drama",USA,"English, Russian",15000000.0,35509515.0,35509515.0,7.1,34513,"Kenneth Fearing, Robert Garland",Orion Pictures,"Kevin Costner, Gene Hackman, Sean Young, Will ...",125.0,72.0,20509515.0
22,tt0494652,"Welcome Home, Roscoe Jenkins",2008,"Comedy, Romance",USA,English,35000000.0,43655418.0,42436517.0,5.5,13315,Malcolm D. Lee,Universal Pictures,"Martin Lawrence, James Earl Jones, Margaret Av...",45.0,74.0,8655418.0
25,tt0285869,Pandora's Box,2002,"Drama, Thriller",USA,English,800000.0,881950.0,881950.0,4.9,629,"Gregory Ramon Anderson, Gregory Ramon Anderson",Rainforest Films,"Chrystale Wilson, Tyson Beckford, Joey Lawrenc...",17.0,5.0,81950.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28472,tt2611626,Force of Execution,2013,"Action, Crime",USA,English,8000000.0,87122.0,NaN,4.4,2941,"Richard Beattie, Michael Black",Voltage Pictures,"Steven Seagal, Ving Rhames, Danny Trejo, Bren ...",35.0,34.0,-7912878.0
28480,tt1706593,Chronicle,2012,"Drama, Sci-Fi, Thriller",USA,English,12000000.0,126636097.0,64575175.0,7.0,237285,"Max Landis, Max Landis",Twentieth Century Fox,"Dane DeHaan, Alex Russell, Michael B. Jordan, ...",519.0,427.0,114636097.0
28485,tt7975244,Jumanji: The Next Level,2019,"Action, Adventure, Comedy",USA,English,125000000.0,796575993.0,316831246.0,6.7,168698,"Jake Kasdan, Jeff Pinkner",Matt Tolmach Productions,"Dwayne Johnson, Kevin Hart, Jack Black, Karen ...",940.0,241.0,671575993.0
28487,tt1369706,The Ward,2010,"Horror, Mystery, Thriller",USA,English,10000000.0,5343820.0,NaN,5.6,39789,"Michael Rasmussen, Shawn Rasmussen",FilmNation Entertainment,"Amber Heard, Mamie Gummer, Danielle Panabaker,...",190.0,263.0,-4656180.0
28489,tt0283026,Swimfan,2002,"Drama, Thriller",USA,English,10000000.0,34411240.0,28564995.0,5.1,18771,"Charles F. Bohl, Phillip Schneider",Twentieth Century Fox,"Jesse Bradford, Erika Christensen, Shiri Apple...",216.0,88.0,24411240.0

## Filtrar Linhas

Usamos indexação booleana ou o metodo .query() para numeros e .str para strings

In [ ]:
# Usando indexação booleana
imdb_df[imdb_df['nota_imdb'] > 9.0]

,id,titulo,ano,data_lancamento,generos,duracao,pais,idioma,gastos,receita,receita_eua,nota_imdb,num_avaliacoes,direcao,roteiro,producao,elenco,descricao,num_criticas_publico,num_criticas_critica
14182,tt0111161,The Shawshank Redemption,1994,1995-02-10,Drama,142,USA,English,25000000.0,28815245.0,28699976.0,9.3,2278845,Frank Darabont,"Stephen King, Frank Darabont",Castle Rock Entertainment,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,8232.0,164.0
20447,tt0068646,The Godfather,1972,1972-09-21,"Crime, Drama",175,USA,"English, Italian, Latin",6000000.0,246120974.0,134966411.0,9.2,1572674,Francis Ford Coppola,"Mario Puzo, Francis Ford Coppola",Paramount Pictures,"Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...,3977.0,253.0
26129,tt5980638,The Transcendents,2018,2020-06-19,"Music, Mystery, Thriller",96,USA,English,90000.0,1090.0,1090.0,9.2,1450,Derek Ahonen,Derek Ahonen,NaN,"Rob Franco, Savannah Welch, Kathy Valentine, W...","Roger, a Rasputin-like drifter, is in search o...",3.0,4.0

In [ ]:
imdb_df[["titulo","ano","nota_imdb"]].query('nota_imdb > 8.5 and ano >= 2010')

                          titulo   ano  nota_imdb
15618  George Takei's Allegiance  2016        8.6
26129          The Transcendents  2018        9.2

In [ ]:
# para retornar generos de Ação ou terror
imdb_df[imdb_df['generos'].str.contains("Action", "Horror")].head()
# imdb_df[imdb_df['generos'].isin(["Action", "Horror"])].head()

,id,titulo,ano,data_lancamento,generos,duracao,pais,idioma,gastos,receita,receita_eua,nota_imdb,num_avaliacoes,direcao,roteiro,producao,elenco,descricao,num_criticas_publico,num_criticas_critica
21,tt0093640,No Way Out,1987,1987-12-11,"Action, Crime, Drama",114,USA,"English, Russian",15000000.0,35509515.0,35509515.0,7.1,34513,Roger Donaldson,"Kenneth Fearing, Robert Garland",Orion Pictures,"Kevin Costner, Gene Hackman, Sean Young, Will ...",A coverup and witchhunt occur after a politici...,125.0,72.0
52,tt0069762,Badlands,1973,1977-03-05,"Action, Crime, Drama",94,USA,"English, Spanish",450000.0,54396.0,NaN,7.8,63933,Terrence Malick,Terrence Malick,Warner Bros.,"Martin Sheen, Sissy Spacek, Warren Oates, Ramo...",An impressionable teenage girl from a dead-end...,234.0,140.0
87,tt0090022,Silverado,1985,1986-01-16,"Action, Crime, Drama",133,USA,English,26000000.0,32192570.0,32192570.0,7.2,37166,Lawrence Kasdan,"Lawrence Kasdan, Mark Kasdan",Columbia Pictures,"Kevin Kline, Scott Glenn, Kevin Costner, Danny...",A misfit bunch of friends come together to rig...,186.0,58.0
117,tt7374952,El Chicano,2018,2020-08-06,"Action, Crime, Drama",108,USA,English,8000000.0,1404646.0,1400603.0,5.3,1016,Ben Hernandez Bray,"Ben Hernandez Bray, Joe Carnahan",WarParty Films,"Logan Arevalo, Julian Bray, Adolfo Alvarez, Ma...",A pair of twin brothers from East L.A. choose ...,27.0,19.0
186,tt1181795,Bunraku,2010,2011-11-30,"Action, Drama, Fantasy",124,USA,"English, Japanese",25000000.0,129706.0,NaN,6.2,18946,Guy Moshe,"Boaz Davidson, Guy Moshe",Snoot Entertainment,"Josh Hartnett, Gackt, Woody Harrelson, Ron Per...",The story of a a young man who has spent his l...,78.0,182.0

In [ ]:
# para retornar generos de TERROR E Ação
imdb_df[(imdb_df['generos'].str.contains("Action")) & (imdb_df['generos'].str.contains("Horror"))][['titulo', 'ano',"generos"]].head()

               titulo   ano                 generos
331        Maniac Cop  1988   Action, Crime, Horror
673   Office Uprising  2018  Action, Comedy, Horror
684      DeepStar Six  1989  Action, Horror, Sci-Fi
1371       Dark Angel  1990   Action, Crime, Horror
1844        Dead Heat  1988  Action, Comedy, Horror

Strings dispoem de varios metodos de manipulação, vamos destacar alguns:

*   `.startswith() , .endswith() e .str.contains()` : seleciona as linhas baseado no inicio, fim o u que contenha um fragmento de str, aceita Expressões Regulares.
*   `.str.strip()`: Remove espaços em branco do início E do fim da string.
*   `.str.lstrip()`: Remove espaços em branco apenas do início
*   `.str.rstrip()`: Remove espaços em branco apenas do fim
*   `.str.replace('texto_antigo', 'texto_novo')`: Substitui todas as ocorrências de um texto por outro.
*  ` .str.split('delimitador')`: Divide a string e retorna uma lista, o argumento `expand=True` ja cria direto no dataframe as colunas.
*   `.str.extract('(regex)')`: Permite usar Expressões Regulares para extrarir informações
*   `.str.get(i)`:  Pega a palavra na posição i da lista.



PAra mais info sobre expressões regulares: [regex](https://media.datacamp.com/legacy/image/upload/v1665049611/Marketing/Blog/Regular_Expressions_Cheat_Sheet.pdf)

In [ ]:
# encontrar filmes que terminam com a letra S

imdb_df[imdb_df['titulo'].str.endswith('s')][['titulo', 'ano']]

                             titulo   ano
4                    Broadcast News  1987
22     Welcome Home, Roscoe Jenkins  2008
52                         Badlands  1973
72      Even Cowgirls Get the Blues  1993
156                  Racing Stripes  2005
...                             ...   ...
28280               Blazing Saddles  1974
28334         The Hollywood Knights  1980
28373                Twelve Monkeys  1995
28392           Brewster's Millions  1985
28445                 Explicit Ills  2008

[813 rows x 2 columns]

In [ ]:
# por exemplo, não pdoe ter "," nos meus titulos
imdb_df['titulo'].str.replace(', ', '_')

4                     Broadcast News
11                 Me_Myself & Irene
21                        No Way Out
22       Welcome Home_Roscoe Jenkins
25                     Pandora's Box
                    ...
28472             Force of Execution
28480                      Chronicle
28485        Jumanji: The Next Level
28487                       The Ward
28489                        Swimfan
Name: titulo, Length: 4732, dtype: object

In [ ]:
#Transformar generos em uma lista (.split)
imdb_df_com_lista = imdb_df.assign(generos=imdb_df['generos'].str.split(','))
display(imdb_df_com_lista.head())
imdb_df_com_lista.explode("generos").head() # duplica a linha com base na lista

,id,titulo,ano,data_lancamento,generos,duracao,pais,idioma,gastos,receita,receita_eua,nota_imdb,num_avaliacoes,direcao,roteiro,producao,elenco,descricao,num_criticas_publico,num_criticas_critica
4,tt0092699,Broadcast News,1987,1988-04-01,"[Comedy, Drama, Romance]",133,USA,"English, Spanish, French, German",20000000.0,67331309.0,51249404.0,7.2,26257,James L. Brooks,James L. Brooks,Amercent Films,"William Hurt, Albert Brooks, Holly Hunter, Rob...",Take two rival television reporters: one hands...,142.0,62.0
11,tt0183505,"Me, Myself & Irene",2000,2000-09-08,[Comedy],116,USA,"English, German",51000000.0,149270999.0,90570999.0,6.6,219069,"Bobby Farrelly, Peter Farrelly","Peter Farrelly, Mike Cerrone",Twentieth Century Fox,"Jim Carrey, Renée Zellweger, Anthony Anderson,...",A nice-guy cop with Dissociative Identity Diso...,502.0,161.0
21,tt0093640,No Way Out,1987,1987-12-11,"[Action, Crime, Drama]",114,USA,"English, Russian",15000000.0,35509515.0,35509515.0,7.1,34513,Roger Donaldson,"Kenneth Fearing, Robert Garland",Orion Pictures,"Kevin Costner, Gene Hackman, Sean Young, Will ...",A coverup and witchhunt occur after a politici...,125.0,72.0
22,tt0494652,"Welcome Home, Roscoe Jenkins",2008,2008-02-08,"[Comedy, Romance]",104,USA,English,35000000.0,43655418.0,42436517.0,5.5,13315,Malcolm D. Lee,Malcolm D. Lee,Universal Pictures,"Martin Lawrence, James Earl Jones, Margaret Av...",Dr. RJ Stevens is a talk show host who visits ...,45.0,74.0
25,tt0285869,Pandora's Box,2002,2002-09-27,"[Drama, Thriller]",103,USA,English,800000.0,881950.0,881950.0,4.9,629,Rob Hardy,"Gregory Ramon Anderson, Gregory Ramon Anderson",Rainforest Films,"Chrystale Wilson, Tyson Beckford, Joey Lawrenc...",Mia DuBois (Calhoun) is a walking cliché--a su...,17.0,5.0

,id,titulo,ano,data_lancamento,generos,duracao,pais,idioma,gastos,receita,receita_eua,nota_imdb,num_avaliacoes,direcao,roteiro,producao,elenco,descricao,num_criticas_publico,num_criticas_critica
4,tt0092699,Broadcast News,1987,1988-04-01,Comedy,133,USA,"English, Spanish, French, German",20000000.0,67331309.0,51249404.0,7.2,26257,James L. Brooks,James L. Brooks,Amercent Films,"William Hurt, Albert Brooks, Holly Hunter, Rob...",Take two rival television reporters: one hands...,142.0,62.0
4,tt0092699,Broadcast News,1987,1988-04-01,Drama,133,USA,"English, Spanish, French, German",20000000.0,67331309.0,51249404.0,7.2,26257,James L. Brooks,James L. Brooks,Amercent Films,"William Hurt, Albert Brooks, Holly Hunter, Rob...",Take two rival television reporters: one hands...,142.0,62.0
4,tt0092699,Broadcast News,1987,1988-04-01,Romance,133,USA,"English, Spanish, French, German",20000000.0,67331309.0,51249404.0,7.2,26257,James L. Brooks,James L. Brooks,Amercent Films,"William Hurt, Albert Brooks, Holly Hunter, Rob...",Take two rival television reporters: one hands...,142.0,62.0
11,tt0183505,"Me, Myself & Irene",2000,2000-09-08,Comedy,116,USA,"English, German",51000000.0,149270999.0,90570999.0,6.6,219069,"Bobby Farrelly, Peter Farrelly","Peter Farrelly, Mike Cerrone",Twentieth Century Fox,"Jim Carrey, Renée Zellweger, Anthony Anderson,...",A nice-guy cop with Dissociative Identity Diso...,502.0,161.0
21,tt0093640,No Way Out,1987,1987-12-11,Action,114,USA,"English, Russian",15000000.0,35509515.0,35509515.0,7.1,34513,Roger Donaldson,"Kenneth Fearing, Robert Garland",Orion Pictures,"Kevin Costner, Gene Hackman, Sean Young, Will ...",A coverup and witchhunt occur after a politici...,125.0,72.0

In [ ]:
# vamos encontrar titulos que tenham data de anos com 4 digitos
imdb_df[imdb_df['titulo'].str.contains(r'\d{4}')]['titulo']

1093                               1408
2116                       2001 Maniacs
2841                     Murder at 1600
2924                      Class of 1999
4142                Blues Brothers 2000
5044              House of 1000 Corpses
5110                       Dracula 2000
6171                     Dystopia: 2013
10439              2307: Winter's Dream
11503                           Mr 3000
12301                     Fantasia 2000
13518    2010: The Year We Make Contact
16252                              2012
16856           3000 Miles to Graceland
23461                          THX 1138
27283                              1941
Name: titulo, dtype: object

## Criação e modificação de colunas (variaveis, atributos)

Destaco agora a importancia de conhecer o contexto do tema, uma das principais atribuições de um cientista de dados, a Engenharia de recurso, que conciste na capacidade de obter novas variaveis (com relevancia) apartir do conjunto de dados.

In [ ]:
#Metodo direto, modificando o DataFrame original
imdb_df['lucro'] = imdb_df['receita'] - imdb_df['gastos'] # determinar o lucro do filme
imdb_df[["titulo","ano","nota_imdb","lucro"]].sort_values(by='lucro',ascending=False).head()

,titulo,ano,nota_imdb,lucro
1022,Avatar,2009,7.8,2.553439e+09
18240,Avengers: Endgame,2019,8.4,2.441801e+09
7315,Star Wars: Episode VII - The Force Awakens,2015,7.9,1.823224e+09
593,Avengers: Infinity War,2018,8.4,1.727360e+09
1727,Jurassic World,2015,7.0,1.520401e+09

In [ ]:
# Usando .assign() (cria um novo DataFrame, ideal para encadeamento)
df_com_lucro = imdb_df.assign(
    lucro_milhoes = lambda df: (df['receita'] - df['gastos']) / 1_000_000,
    gastos_milhoes = lambda df: df['gastos'] / 1_000_000,
    receita_milhoes = lambda df: df['receita'] / 1_000_000
)

df_com_lucro[['titulo', 'lucro_milhoes']].head()

                          titulo  lucro_milhoes
4                 Broadcast News      47.331309
11            Me, Myself & Irene      98.270999
21                    No Way Out      20.509515
22  Welcome Home, Roscoe Jenkins       8.655418
25                 Pandora's Box       0.081950

In [ ]:
# com aplicação de logica condicional,
# necessario a biblioteca numpy
import numpy as np

#Ex: nova variavel com condição de prejuizo
df_com_prejuizo = df_com_lucro.assign(
    teve_prejuizo = lambda df: np.where(df['lucro'] < 0, 'Sim', 'Não')
)

display(df_com_prejuizo[['titulo', 'lucro_milhoes', 'teve_prejuizo']].head())
df_com_prejuizo[['titulo', 'lucro_milhoes', 'teve_prejuizo']][df_com_prejuizo['teve_prejuizo']=="Sim"] # caso quiser ver apenas os que tiverem prejuizo
df_com_prejuizo[['titulo', 'lucro_milhoes', 'teve_prejuizo',"nota_imdb"]].query('teve_prejuizo=="Sim" and nota_imdb>8').head() # bons filmes com prejuizo

                          titulo  lucro_milhoes teve_prejuizo
4                 Broadcast News      47.331309           Não
11            Me, Myself & Irene      98.270999           Não
21                    No Way Out      20.509515           Não
22  Welcome Home, Roscoe Jenkins       8.655418           Não
25                 Pandora's Box       0.081950           Não

                      titulo  lucro_milhoes teve_prejuizo  nota_imdb
257            The Gold Rush      -0.896084           Sim        8.2
864             12 Angry Men      -0.349424           Sim        8.9
2532  Sweet Smell of Success      -3.392296           Sim        8.1
3544            Modern Times      -1.042312           Sim        8.5
7361   Judgment at Nuremberg      -2.987820           Sim        8.2

## Agrupamento e sumarização


*    padrão em pandas é df.groupby('coluna')['outra_coluna'].mean()
*   para múltiplas agregações: df.groupby('coluna').agg(nova_coluna=('outra_coluna', 'mean'))

In [ ]:
#Receita media por Ano dos filmes
imdb_df.groupby('ano')['receita'].mean().sort_values(ascending=False)

# deversas informações por Ano
imdb_df.groupby('ano').agg(
    nota_media=('nota_imdb', 'mean'),
    desvio_padrao_nota=('nota_imdb', 'std'),
    orcamento_medio=('gastos', 'mean'),
    numero_de_filmes=('titulo', 'count')
).sort_values('numero_de_filmes', ascending=False)

      nota_media  desvio_padrao_nota  orcamento_medio  numero_de_filmes
ano
2007    5.950296            1.171391     2.633309e+07               169
2006    5.886667            1.123992     2.470888e+07               165
2009    5.888344            1.129262     2.707389e+07               163
2013    6.046250            1.056212     3.276539e+07               160
2008    5.940385            1.079234     2.548364e+07               156
...          ...                 ...              ...               ...
1925    8.200000                 NaN     9.230000e+05                 1
1932    7.900000                 NaN     3.106070e+05                 1
1938    7.900000                 NaN     1.073000e+06                 1
1923    7.000000                 NaN     3.510000e+05                 1
1966    8.000000                 NaN     7.500000e+06                 1

[95 rows x 4 columns]

## Merge
juntar data frames
![exemplo pelo ID](https://statisticsglobe.com/wp-content/uploads/2021/12/join-types-python-merge-programming.png)

In [ ]:
#Vamos criar uma tabela com a nota média por Ano
nota_media_por_ano = imdb_df.groupby('ano').agg(
    nota_media_anual=('nota_imdb', 'mean')
).reset_index() # .reset_index() transforma a coluna de grupo 'ano' em uma coluna normal

display(nota_media_por_ano.head())


# Agora vamos juntar (merge) essa informação de volta ao DataFrame original
imdb_com_nota_media = pd.merge(
    imdb_df,
    nota_media_por_ano,
    on='ano', # a chave da junção
    how='left'   # tipo de join (left, right, inner, outer)
)


display(imdb_com_nota_media[['ano','titulo', 'nota_imdb', 'nota_media_anual']].head())

    ano  nota_media_anual
0  1921              7.75
1  1923              7.00
2  1925              8.20
3  1927              7.80
4  1928              8.10

    ano                        titulo  nota_imdb  nota_media_anual
0  1987                Broadcast News        7.2          6.225287
1  2000            Me, Myself & Irene        6.6          6.080833
2  1987                    No Way Out        7.1          6.225287
3  2008  Welcome Home, Roscoe Jenkins        5.5          5.940385
4  2002                 Pandora's Box        4.9          6.201613

###Atividade



1.    Qual o valor da receita total de cada produtora por ano?
2.   Quais idiomas foram usados em ao menos 100 filmes, diga quantas produções foram feitas usando esses idiomas
3. retorne apenas os numeros em float do dataframe:


```

 df = pd.DataFrame({
    'valor': [
        "7",
        "7.0",
        "R$7.00",
        "7 a"
    ]
})
```

In [ ]:
imdb_df.groupby(['producao', 'ano'])['receita'].sum().reset_index().sort_values(by=['ano','producao'])

                         producao   ano     receita
649   Charles Chaplin Productions  1921     26916.0
1881   Metro Pictures Corporation  1921   9183673.0
650   Charles Chaplin Productions  1923     11233.0
651   Charles Chaplin Productions  1925     26916.0
1246         Fox Film Corporation  1927    121107.0
...                           ...   ...         ...
1396    Grodnik /Aloe Productions  2020     49104.0
1668     Kevin Downes Productions  2020  13681524.0
2257        Passage Pictures (II)  2020     79603.0
2499         Rumble Riot Pictures  2020    507974.0
2677                        TRI G  2020   1472195.0

[3195 rows x 3 columns]

In [ ]:
# Temos filmes com mais de um diretor, vamos criar a lista depois explode
df_com_listas = imdb_df.assign(idioma=imdb_df['idioma'].str.split(','))
df_explodido = df_com_listas.explode('idioma')

# Limpando espaços em branco extras dos nomes dos diretores
df_explodido['idioma'] = df_explodido['idioma'].str.strip()

#contagem
df_explodido['idioma'].value_counts().reset_index().query('count > 100')

    idioma  count
0  English   4716
1  Spanish    440
2   French    276
3   German    159
4  Italian    133
5  Russian    117

In [ ]:
 df = pd.DataFrame({ 'valor': [
 "7",
 "7.0",
 "R$7.00",
 "7 a"
] })


# usar regex
df['valor']=df['valor'].str.extract(r'([+-]?\d*\.?\d+)')
print(df)
pd.to_numeric(df['valor'])

  valor
0     7
1   7.0
2  7.00
3     7

0    7.0
1    7.0
2    7.0
3    7.0
Name: valor, dtype: float64

## atividade
Qual diretor tem os filmes com a melhor nota, “Quentin Tarantino” ou “Steven Spielberg”, quais outras métricas você poderia usar para ajudar a definir qual é melhor e o que pode trazer incerteza avaliação. (qual você contrataria?)

In [ ]:
sumario_final = (
    imdb_df[imdb_df['direcao'].isin(["Quentin Tarantino", "Steven Spielberg"])]
    .groupby('direcao')
    .agg(
        nota_media=('nota_imdb', 'mean'),
        desvio=('nota_imdb', 'std'),
        numero_filmes=('titulo', 'size'),
        numero_criticas=('num_criticas_publico', 'sum'),
        gasto_medio=('gastos', 'mean')
    )
    .assign( # .assign() permite criar novas colunas de forma encadeada
        relacao_nota_orcamento = lambda df: (df['nota_media'] / df['gasto_medio']) * 10000000
    )
    .reset_index()
)

display(sumario_final)

,direcao,nota_media,desvio,numero_filmes,numero_criticas,gasto_medio,relacao_nota_orcamento
0,Quentin Tarantino,8.150000,0.492950,6,8791.0,3.253333e+07,2.505123
1,Steven Spielberg,7.428571,0.840323,21,19569.0,5.064286e+07,1.466855

## Trabalhando com datas

è recorrente o trabalho com datas e temos que ter algumas atenções especiais a ela, vide o problema encontrado abaixo na hora de converter a string para datetime

In [ ]:
# Convertendo a coluna de string para datetime
imdb_df['data_lancamento'] = pd.to_datetime(imdb_df['data_lancamento'])

ValueError: time data "2018" doesn't match format "%Y-%m-%d", at position 14. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
   # vamos forçar os erros virarem NaT (Not a Time)
   imdb_df['data_lancamento'] = pd.to_datetime(imdb_df['data_lancamento'], errors='coerce')

   imdb_df['data_lancamento']

4       1988-04-01
11      2000-09-08
21      1987-12-11
22      2008-02-08
25      2002-09-27
           ...
28472   2014-03-13
28480   2012-05-09
28485   2019-12-25
28487   2011-04-01
28489   2003-05-30
Name: data_lancamento, Length: 4732, dtype: datetime64[ns]

Uma vez que temos o formato datetime, podemos usar o acesso `.dt` que dispoe de inumeros metodos para operar as datas,m mais infos em [Pandas Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.month.html)

In [ ]:
# mes

imdb_df['data_lancamento'].dt.month.astype("Int64") # se não vem float

4         4
11        9
21       12
22        2
25        9
         ..
28472     3
28480     5
28485    12
28487     4
28489     5
Name: data_lancamento, Length: 4732, dtype: Int64

In [ ]:
#è ano bisexto
imdb_df['data_lancamento'].dt.is_leap_year

4         True
11        True
21       False
22        True
25       False
         ...
28472    False
28480     True
28485    False
28487    False
28489    False
Name: data_lancamento, Length: 4732, dtype: bool

In [ ]:
# Criando uma coluna com o número do dia da semana (Segunda=0, Domingo=6),day_name() para nome
imdb_df['dia_da_semana_num'] = imdb_df['data_lancamento'].dt.day_name()
imdb_df['dia_da_semana_num']

4           Friday
11          Friday
21          Friday
22          Friday
25          Friday
           ...
28472     Thursday
28480    Wednesday
28485    Wednesday
28487       Friday
28489       Friday
Name: dia_da_semana_num, Length: 4732, dtype: object

Podemos usar o `.dt.strftime`, poara formatar como quisermos a datas

`%d`: Dia do mês (ex: 01, 14, 30)

`%m`: Mês como número (ex: 05, 10, 12)

`%Y`: Ano com 4 dígitos (ex: 1994)

`%y`: Ano com 2 dígitos (ex: 94)

`%B`: Nome completo do mês

`%A`: Nome completo do dia da semana

In [ ]:
#converter o formato de interesse
imdb_df['data_lancamento'].dt.strftime('%d/%m/%Y')

4        01/04/1988
11       08/09/2000
21       11/12/1987
22       08/02/2008
25       27/09/2002
            ...
28472    13/03/2014
28480    09/05/2012
28485    25/12/2019
28487    01/04/2011
28489    30/05/2003
Name: data_lancamento, Length: 4732, dtype: object

### atividade

Quantos são os filmes lançados por dia da semana, isso influencia na nota?

In [ ]:
imdb_df['dia_da_semana_num'].value_counts()

dia_da_semana_num
Friday       2954
Thursday      878
Wednesday     437
Saturday      177
Tuesday       140
Monday         66
Sunday         54
Name: count, dtype: int64

In [ ]:
imdb_df.groupby('dia_da_semana_num').agg(
    nota_media=('nota_imdb', lambda x: x.mean().round(2)), # é possivel usar função para operação mais complexas
    N=("nota_imdb","size")
)

                   nota_media     N
dia_da_semana_num
Friday                   6.12  2954
Monday                   6.42    66
Saturday                 6.29   177
Sunday                   5.82    54
Thursday                 6.38   878
Tuesday                  6.16   140
Wednesday                6.34   437

## exercicios
exercitar um pouco sobre series temporais nos dados da iconica temproada do Lakers(NBA) de 2008-2009.

"https://www.smartana.org/da/data/lakers.csv"


* Qual foi o tempo mais curto que o lakers levou para fazer o primeiro ponto?

* Qual o tempo médio para o primeiro falta do lakers?

In [ ]:
# para baixar
!wget -q -O lakers.csv https://www.smartana.org/da/data/Publication.csv

In [ ]:
# importar direto do link
lakers=pd.read_csv("https://www.smartana.org/da/data/lakers.csv")
lakers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34624 entries, 0 to 34623
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       34624 non-null  int64
 1   opponent   34624 non-null  object
 2   game_type  34624 non-null  object
 3   time       34624 non-null  object
 4   period     34624 non-null  int64
 5   etype      34624 non-null  object
 6   team       34624 non-null  object
 7   player     29231 non-null  object
 8   result     16888 non-null  object
 9   points     34624 non-null  int64
 10  type       24242 non-null  object
 11  x          13067 non-null  float64
 12  y          13067 non-null  float64
dtypes: float64(2), int64(3), object(8)
memory usage: 3.4+ MB

In [ ]:
pd.to_datetime(lakers['time'],format='%M:%S').dt.minute

0        12
1        11
2        11
3        11
4        11
         ..
34619     0
34620     0
34621     0
34622     0
34623     0
Name: time, Length: 34624, dtype: int32

In [ ]:
lakers["tempo_total"]=(lakers["period"])*720-pd.to_datetime(lakers['time'],format='%M:%S').dt.minute*60-pd.to_datetime(lakers['time'],format='%M:%S').dt.second
lakers['tempo_total']

0           0
1          21
2          23
3          35
4          37
         ...
34619    2838
34620    2838
34621    2853
34622    2859
34623    2860
Name: tempo_total, Length: 34624, dtype: int64

In [ ]:
lakers[(lakers['team'] == 'LAL') & (lakers['points'] == 3)].groupby('date')['tempo_total'].min().min()
#saber a data: lakers[(lakers['team'] == 'LAL') & (lakers['points'] == 3)].groupby('date')['tempo_total'].min().reset_index().sort_values(by="tempo_total")

18

In [ ]:
lakers[lakers["date"]==20090218	].head(5)

,date,opponent,game_type,time,period,etype,team,player,result,points,type,x,y,tempo_total
21864,20090218,GSW,away,12:00,1,jump ball,OFF,NaN,NaN,0,NaN,NaN,NaN,0
21865,20090218,GSW,away,11:42,1,shot,LAL,Derek Fisher,made,3,3pt,48.0,5.0,18
21866,20090218,GSW,away,11:23,1,shot,GSW,Stephen Jackson,missed,0,layup,27.0,6.0,37
21867,20090218,GSW,away,11:23,1,rebound,GSW,NaN,NaN,0,NaN,NaN,NaN,37
21868,20090218,GSW,away,11:23,1,foul,LAL,Luke Walton,NaN,0,loose ball,NaN,NaN,37